### ISSUE TITLE
Documentation heavily misleading

### ISSUE THREAD

**Issue by Mecanik** [ovh/php-ovh#102]
First example:

-  /ip/{ip}

The Documentation says:

`$result = $ovh->get('/ip/{ip}');`

However this is wrong because it should be:

`$result = $ovh->get('/ip', ['ip' => '']);`

Then you have the other problem of IP Blocks with "/" in the call. You cannot use it like this, you just can't.

Example:

`$result = $ovh->get('/ip/{ip}/antihack/{ipBlocked}');`

Because of that you will always get:

`Got an invalid (or empty) URL`

So for this reason with now you have to to do something like:

`$result = $ovh->get('/ip/'.IP_BLOCK_HERE.'/antihack/'.IP_HERE.'');`

Then you have the problem with access rights, for example if I grant GET on /ip, I should have access to all sub functions.

But at the moment I get:

`{"message":"This call has not been granted","httpCode":"403 Forbidden","errorCode":"NOT_GRANTED_CALL"}`

And plenty other issues, I`m already tired trying to fix and use the API not to report here.

You should make it properly, and also release a new version because the last release is from 2016.

**Comment by rbeuque74** [comment]
Hello,

`$result = $ovh->get('/ip/{ip}');` is different from `$result = $ovh->get('/ip', ['ip' => '']);`
The first one returns the information of an IP address, the second one list all the ip addresses matching a given filter.

Regarding `$result = $ovh->get('/ip/{ip}/antihack/{ipBlocked}');`, you should URL-encode your IP address (transforming `127.0.0.1/32` into `127.0.0.1%2F32`) so the slashes are not interpreted as path delimiters.

Closing this issue as there is no issues on `php-ovh` here.

Romain
