### ISSUE TITLE
[ports] Range Data is not a hash for a complex type

### ISSUE THREAD

**Issue by sk7866** [ovh/php-ovh#105]
Can't use post api to add game firewall rules facing this issue.

It works fine on http but in php it's not working 

[ports] Range Data is not a hash for a complex type.

I'm entering this `$result = $ovh->post('/ip/51.79.190.100/game/51.79.190.100/rule', array(
                    'ports' => '{"from":9999,"to":9999}', // The UDP port range to apply the rule on (type: complexType.Range<long>)
                    'protocol' => 'teamspeak3', // The protocol running behind the given port (type: ip.GameMitigationRuleProtocolEnum)
                ));`

**Comment by rbeuque74** [comment]
Hello,
Please change your code to

```php
$result = $ovh->post('/ip/51.79.190.100/game/51.79.190.100/rule', array( 'ports' => {"from":9999,"to":9999}, // The UDP port range to apply the rule on (type: complexType.Range<long>)
     'protocol' => 'teamspeak3', // The protocol running behind the given port (type: ip.GameMitigationRuleProtocolEnum)
 ));
```

Remove the quote around the value of `ports`
