### ISSUE TITLE
How to update script and credentials

### ISSUE THREAD

**Issue by spyesx** [ovh/php-ovh#107]
Hi !

The documentation provides a link to create API Keys for our scripts.

> Visit https://api.ovh.com/createToken/index.cgi?GET=/me to get your credentials

I did it, it worked. Good.

However, how do we update our "scripts"? Basically, I need to allow more rights and modify the validity.

I could create a new one but I'd have to delete this "script" and here comes a new question. How do we delete a "script"?

**Comment by rbeuque74** [comment]
Hello,

Sorry for late answer.

You can delete OVH API applications using: [https://api.ovh.com/console/#/me/api/application/%7BapplicationId%7D~DELETE](https://api.ovh.com/console/#/me/api/application/%7BapplicationId%7D%7EDELETE)
You can delete OVH api credentials using: [https://api.ovh.com/console/#/me/api/credential/%7BcredentialId%7D~DELETE](https://api.ovh.com/console/#/me/api/credential/%7BcredentialId%7D%7EDELETE)

Thanks,
Romain

**Comment by spyesx** [comment]
Hi @rbeuque74, thank you :)
