### ISSUE TITLE
RunAbove CreateToken Link seems down

### ISSUE THREAD

**Issue by wiserweb** [ovh/php-ovh#11]
RunAbove CreateToken link seems down.

https://api.runabove.com/createToken/

**Comment by VincentCasse** [comment]
Yes, you're right!

I check why this page have disappear.

**Comment by gentlemon** [comment]
it's still down.

**Comment by gierschv** [comment]
@gentlemon Hi, I'm checking with our team. However you don't need this page to get started with the RunAbove API, check out the [following example](https://github.com/ovh/php-ovh#how-to-login-as-a-user) to create a consumer key for your script. Please feel free to drop a comment here if you need some help or if you have any question.

**Comment by gierschv** [comment]
@gentlemon @wiserweb This page is not yet implemented, we'll update this issue once this one will be online. As a I said below, please check out the [following example](https://github.com/ovh/php-ovh#how-to-login-as-a-user) to get started with the RunAbove API with this PHP wrapper.

**Comment by gentlemon** [comment]
Well, I know I don't need it because I am familiar with the OVH API. But people trying to get started with runabove API following the tutorial on the website will probably be upset.
