### ISSUE TITLE
PHP8 Compatibility

### ISSUE THREAD

**Issue by slaiddominio** [ovh/php-ovh#119]
Hello, my name is Leandro de França, I am a project manager at DataFast Sistemas LTDA, we are your customers.

I need to use this repository in one of our startups.
Does it support PHP8?

**Comment by rbeuque74** [comment]
Hello @slaiddominio ,
Sorry for late answer.
There is no incompatibilities known at this day with PHP8.
You can use this module with PHP8.

I will close this issue, feel free to reopen it if you find an issue when you are testing it !

Romain
