### ISSUE TITLE
how to get OVH Application Key

### ISSUE THREAD

**Issue by hosamalzagh** [ovh/php-ovh#126]
where i can see OVH Application Key

**Comment by deathiop** [comment]
As the problem is not related to the php-ovh wrapper, I will close this issue, and let you send your issue to our customer mailing-list, [api@ml.ovh.net](mailto:api@ml.ovh.net). You can subscribe by sending an email to [api-subscribe@ml.ovh.net](mailto:api-subscribe@ml.ovh.net).
