### ISSUE TITLE
Error while refreshing do domain

### ISSUE THREAD

**Issue by stephane888** [ovh/php-ovh#140]
Error while refreshing do domain
We use this API to generate subdomains.

The endpoint "/v1/domain/zone/{zone_name}/refresh" returns "Syntax error"

After analysis, we see that the refresh action was carried out successfully with a status code 204, the subdomain is indeed accessible. The problem seems to arise at the level of the interpretation of the response (decodeResponse).

Please check this out :)

**Comment by OctaYann** [comment]
Hi, 

same here, i fixed it in my codebase, i'll make a pr

OVH now send a 204 no content response when we call domain/zone/{zoneName}/refresh, that's why.

But obviously and as usual doesn't care about us ...

**Comment by OctaYann** [comment]
I've just submited a PR, hope this can be merged during next week #141

**Comment by deathiop** [comment]
Hi there,
Resolved in #140.
Released in v3.3.0.

Have a nice day!
