### ISSUE TITLE
a way to get a ready to deploy archive

### ISSUE THREAD

**Issue by niconil** [ovh/php-ovh#15]
If i use a web hosting pro
i have a lot of difficulty to deplay php-ovh wrapper

how to install/deploy php-ovh 
i've just a ftp access to the webserver

i'm surprise to not find easely an archive ready to deploy
may i build an archive on a vps virtual server and use it on my web hosting pro ?

**Comment by yadutaf** [comment]
Hi niconil,

Thanks for using php-ovh, AFAIK, the easiest way to deploy composer code using a FTP access is to
1. download all dependencies in a local copy of the project / website
2. upload all project files and dependencies to your hosting

Maybe @VincentCasse a better idea ?

NB: as this is not strictly speaking a bug in php-ovh itself, I close this issue as "invalid" for the record.

**Comment by niconil** [comment]
not a bug but php-ovh could give the recipe to make an installation on a FTP access

when you say 
"download all dependancies" can you list which ones ?

**Comment by VincentCasse** [comment]
Hi niconil,

Unfortunately, we don't have (yet) better solution than create a local repository, deploy all dependencies with composer install and then send it with FTP or SSH. (You should have a ssh access with hosting pro on ovh).

If you use some php framework like Symfony, I believe that Capistrano could deploy a solution with an SSH access.

**Comment by VincentCasse** [comment]
You can now download all the dependencies with composer from our web hosting offers.
You had just connect you with SSH and launch ```composer install```
