### ISSUE TITLE
Problems on Put&Post

### ISSUE THREAD

**Issue by arcronis** [ovh/php-ovh#19]
I try two things 

the first one is Put the rescueMail to server i use the following command 
$content = (object) array(
							"rescueMail"=> "xxx@xxx.com"
							);
							print_r($content);
							$servers = $conn->put('/dedicated/server/'.$servername.'', $content);

i get back a void "1" , after get server details the rescuemail is empty.

Second 

Trying to send content to install/start but i get a error on guzzlehttp

my command

$content = (object) array ("templateName"=> $os,
							"postInstallationScriptLink"=> "http://www.xxxx.com/script.sh",
							"postInstallationScriptReturn"=>"bash script.sh");

							$servers = $conn->post('/dedicated/server/'.$servername.'/install/start', $content);

hope anyone can help

**Comment by VincentCasse** [comment]
Do you always have this problem?
