### ISSUE TITLE
Bad response on GET with params

### ISSUE THREAD

**Issue by johndodev** [ovh/php-ovh#28]
$client->get('/order/cart/'.$cartId.'/domain', ['domain' => $domain]); 

résulte en une jolie 400 : 

> Client error: `GET https://api.ovh.com/1.0/order/cart/977c98a2-7841-4b2d-b385-948ef3e49b51/domain?domain=google.com` resulted in a `400 Bad Request` response: {"errorCode":"INVALID_SIGNATURE","httpCode":"400 Bad Request","message":"Invalid signature"}

Pourtant, 

    $client->get('/order/cart/'.$cartId.'/domain?domain='.$domain); 

fonctionne.

C'est la même url de reqûete qui est généré, je suppose que le soucis est dans le calcule de la signature dans le client.

**Comment by VincentCasse** [comment]
Bonjour johndodev

Effectivement, cette erreur nous a été remonté en interne cette semaine. La pull request [#26](https://github.com/ovh/php-ovh/pull/26) fixe le soucis. Elle devrait être mergée cette après  midi et backportée sur la version 1.x.x

Merci pour la remontée

**Comment by johndodev** [comment]
Okay thx.
