### ISSUE TITLE
Please give examples regarding responder

### ISSUE THREAD

**Issue by e-gaulue** [ovh/php-ovh#29]
Dear community,

In the past, we could give OVH-NIC to anybody and with the managerV3 they were able to deal with the responders of their own email address. This is not possible anymore with the new manager, but you can delegate the whole email management to a NIC. This NIC could be used to connect through the API and deal with those responders.

Then, we could imagine this kind of script:
1. user give the left part of his email address
2. he receives an email with a forged link to the script server (with a key that identifies himself)
3. he fills most of the fields requested for creating a responder but not its email address as we already knows who he is (authentified by email)
4. the script connects with the NIC authorized to manage email and create the responder, then confirms the creation to the user

We could imagine another script to remove any responder linked with an address.

Maybe OVH could help giving example for the 4th point.

Regards,

**Comment by VincentCasse** [comment]
Hi e-gaulue,

This authentication method does not works anymore. But I have a means to delegate rights to edit responders.

With the new API, you can create an authentication token with restricted rights on a account. By example, you can allow a token to access only on  /email/domain/your_own_domain.ovh/responder/email@your_own_domain.ovh.

I can write a script and a tutorial with this example if you want.

Regards

**Comment by e-gaulue** [comment]
Yes please, because I've to say that those token are not really clear for me right now. I've got the feeling we authenticate 3 times... I'm a little bit lost between account and token. But maybe seeing code could help me.

I wan't to provide the above authentication because my users have no idea about their mail password. The account is installed on their computer profile and just work. They don't know what their password is. But if they go on a internal PHP page and ask for a responder giving a email address, they should be the only one to receive it and activate it if there is a link to do so in the email. I can provide this part because I'm used of it, but the API side looks obscur to me.

Maybe the way I want to do it is not the right one because RESTFUL API can provide enough meta data for a PHP script to auto generate forms. I don't know. 

Let me (us) know. Regards.
