### ISSUE TITLE
Response too short

### ISSUE THREAD

**Issue by DracoThuban** [ovh/php-ovh#33]
When a domain is added to the secondary dns, the message is truncated. 
This makes it impossible to know the value of "ownercheck" to take any further action.

**Comment by yadutaf** [comment]
Hi @DracoThuban,

Thanks for taking the time to report this bug. Can you provide a minimal code sample, with fictive data, to reproduce this bug along with a sample answer vs what was actually expected?

This will help us a lot to fix the issue as quickly as possible.

Thanks,

**Comment by DracoThuban** [comment]
Sure.

Code:
$content = (object) array('domain' => "test.com", 'ip' => "127.0.0.1");
print_r( $conn->post('/vps/test99999.vps.ovh.ca/secondaryDnsDomains', $content) );

Output:
{"message":"First we need to verify you are the owner of this domain. To do so, please add a TXT field on your DNS zone  (truncated...)

Expected:
{"message":"First we need to verify you are the owner of this domain. To do so, please add a TXT field on your DNS zone for the domain test.com, with the subdomain 'ownercheck' and the following value: '339ea8d0'. Once done and your zone reloaded, try again (you don't need to wait for DNS propagation)."}

**Comment by rbeuque74** [comment]
Hello,
Closing as stalled. Feel free to reopen if still relevant.

Romain
