### ISSUE TITLE
Why using grunt a JS tool in a full PHP project ?

### ISSUE THREAD

**Issue by shulard** [ovh/php-ovh#35]
Hello !

I discovered that I need to install a node module to be able to test that full php project... I really don't understand why ? It's just too much complexity to just run phpunit, phpcs and phplint...
The complexity which it requires is just useless. Why not using a PHP build tool like [Phing](http://phing.info/) to perform the automation ?

**Comment by VincentCasse** [comment]
Hi @shulard,

That's a good idea to use PHP build tools instead of grunt :).
Do you know how phing works? Have you already use it?

**Comment by shulard** [comment]
Hi,

Yep I know Phing really well :smile: 
If you want I can make a PR to implement it !

The only thing that I'm not sure about is the file watch process used to run the pre-commit task.
