### ISSUE TITLE
Issue with /ip/x.x.x.x/reverse (get/post)

### ISSUE THREAD

**Issue by MartinRaiola** [ovh/php-ovh#46]
Hello,

im getting this issue only with this part of the API.

The test code is:

```php
require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;

$ovh = new Api( $applicationKey,
               $applicationSecret,
               $endpoint,
               $consumer_key);

$rango = 'x.x.x.x/aa';
$ip = 'y.y.y.y';
$ptr = 'servet.domain.tld';

$result = $ovh->post('/ip/'. $rango .'/reverse', array(
   'ipReverse' => $ip,
   'reverse' => $ptr,
));

$result1 = $ovh->get('/ip/'.$rango.'/reverse/'.$ip);

print_r( $result );
print_r( $result1 );
```

But I always get this error:

> PHP Fatal error:  Uncaught exception 'GuzzleHttp\\Exception\\ClientException' with message 'Client error: `GET https://api.ovh.com/1.0/ip/x.x.x.x/aa/reverse/y.y.y.y` resulted in a `404 ObjectNotFound` response:\n{"message":"Got an invalid (or empty) URL"}\n' in /home/admin/web/testing.domain/public_html/modules/addons/ModuloRaiola/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107\nStack trace:\n#0 /home/admin/web/testing.domain/public_html/modules/addons/ModuloRaiola/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))\n#1 /home/admin/web/testing.domain/public_html/modules/addons/ModuloRaiola/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))\n#2 /home/admin/web/testing.domain/public_html/modules/addons/ModuloRaiola/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHa in /home/admin/web/testing.domain/public_html/modules/addons/ModuloRaiola/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107

**Comment by VincentCasse** [comment]
Hi. I think that because your encodage of the ip range is not well encoded.

Can you test with 
`$rango = 'x.x.x.x%2Faa` ?

**Comment by MartinRaiola** [comment]
With this works. Finally we use a urlencode.
