### ISSUE TITLE
ImapCopy error StructImapCopy Data is not a hash for a complex type

### ISSUE THREAD

**Issue by MJBGO** [ovh/php-ovh#50]
Hi !

I'm having some problems with the api and url **email/imapCopy**

This is the code (generated by the api website, removed passwords) : 

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;

$ovh = new Api( 'xxxx',  // Application Key
                'xxxxx',  // Application Secret
                'ovh-eu',      // Endpoint of API OVH Europe (List of available endpoints)
                'xxxxxx'; // Consumer Key

$result = $ovh->post('/email/imapCopy', array(
    'from' => '{"SSL":"false","password":"xxxxx","serverIMAP":"imap.free.fr","account":"xxxx@free.fr"}',
    'to' => '{"SSL":"true","password":"xxxx","serverIMAP":"ssl0.ovh.net","account":"xxxx@xxx.fr"}'
));
```

When I execute the php file, it returns an exception : 

> PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.ovh.com/1.0/email/imapCopy` resulted in a `400 InvalidArgument` response:
{"message":"**[to] StructImapCopy Data is not a hash for a complex type**"}
' in /home/imapcopy/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:111
Stack trace:
#0 /home/imapcopy/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/imapcopy/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/imapcopy/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/imapcopy/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/imapcopy/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleH in /home/imapcopy/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 111

Can someone tell me why ? I'm stuck :( 

Thanks !

**Comment by yadutaf** [comment]
Can you retry with something like:

```php
<?php
require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;

$ovh = new Api( 'xxxx',   // Application Key
                'xxxxx',  // Application Secret
                'ovh-eu', // Endpoint of API OVH Europe (List of available endpoints)
                'xxxxxx'; // Consumer Key

$result = $ovh->post('/email/imapCopy', array(
    "from" => array(
        "SSL" => false,
        "password" => "xxxxx",
        "serverIMAP" => "imap.free.fr",
        "account" => "xxxx@free.fr"
    ),  
    "to" => array(
        "SSL" => true,
        "password" => "xxxx",
        "serverIMAP" => "ssl0.ovh.net",
        "account" => "xxxx@xxx.fr"
    )   
));
```

**Comment by MJBGO** [comment]
Hi,

Works perfectly with a PHP array, thanks !
