### ISSUE TITLE
[QUESTION] Renew domains

### ISSUE THREAD

**Issue by shakaran** [ovh/php-ovh#52]
I am checking some operation in the API Console about domains.

For me it is [very useful](https://api.ovh.com/console/#/domain/%7BserviceName%7D#GET) the [authInfo](https://api.ovh.com/console/#/domain/%7BserviceName%7D/authInfo#GET), unlock, owo, [etc](https://api.ovh.com/console/#/domain/%7BserviceName%7D/nameServer#POST). But it would be a lot useful if I could renew the domains in some way, adding even a money balance to my account or so.

Would be available this at some point, so I can automatize the domain renovations? Other domain providers offers an API for this, and I see a lack of feature on OVH, but I would like stay with OVH too if this gets implemented.

**Comment by yadutaf** [comment]
Have you checked the "order" section of the API ? You'll find usage examples in this repository: https://github.com/ovh/order-cart-examples

**Comment by Rbeuque74** [comment]
No, you won't be able to renew domain via the order section.
Right now, the only API available is to activate the autorenew on your domain service ([POST /domain/{domain}/serviceInfos](https://api.ovh.com/console/#/domain/%7BserviceName%7D/serviceInfos#PUT)) and generate an order to credit your OVH Account: [POST /me/ovhAccount/{ovhAccountId}/creditOrder](https://api.ovh.com/console/#/me/ovhAccount/%7BovhAccountId%7D/creditOrder#POST)

**Comment by shakaran** [comment]
@yadutaf @Rbeuque74 since order api is only in Python or REST, would be available in PHP too?

Also, it seems more complex enable the autorenew and generate the order, instead just a simple "renew" action which directly try to remove the amount from the credit available or fail if not enough founds. I think that it would be a nice feature to implement and more easy to code if you consider it. 

Thanks for your great support and quick replies

**Comment by shakaran** [comment]
BUMP

**Comment by yadutaf** [comment]
Hello @shakaran,

Thank you for taking the time to share this feedback. As this is not directly nor indirectly related to php-ovh, we can sadly not provide you with an answer.

I encourage you to subscribe to the API mailing list (api-subscribe@ml.ovh.net). This will be the best place to continue this discussion.

Have a nice day,
