### ISSUE TITLE
[transferLockStatus] Given data (available) does not belong to the DomainLockStatusEnum enumeration

### ISSUE THREAD

**Issue by shakaran** [ovh/php-ovh#53]
I am trying to update a domain for change the transferLockStatus (to disable or unlock).

I use the following code according to spec in php:

	$domain = 'mydomain.es';
	try
	{ 
		$domain_status = $ovh->put('/domain/' . $domain, ['transferLockStatus' => 'available']);
	}
	catch (GuzzleHttp\Exception\ClientException $e)
	{
		$content = json_decode($e->getResponse()->getBody()->getContents());

		if(isset($content->message))
		{
			echo $content->message . PHP_EOL;
		}
		else 
		{
			echo 'Unknown error message' . PHP_EOL;
		}
	}

As result I get:

    [transferLockStatus] Given data (available) does not belong to the DomainLockStatusEnum enumeration

I don't know which are the valid values, since [DomainLockStatusEnum is not defined](https://api.ovh.com/console/#/domain/%7BserviceName%7D#PUT) in any part in the spec docs. I try passing FALSE with the following code:

	try
	{ 
		$domain_status = $ovh->put('/domain/' . $domain, ['transferLockStatus' => FALSE]);
	}
	catch (GuzzleHttp\Exception\ClientException $e)
	{
		$content = json_decode($e->getResponse()->getBody()->getContents());

		if(isset($content->message))
		{
			echo $content->message . PHP_EOL;
		}
		else 
		{
			echo 'Unknown error message' . PHP_EOL;
		}
	}

Which produces:

    Lock unavailable for your domain

So as far I understand the "unlock" feature is not implemented for the TLD ".es". This is possible to perform via OVH web interface, but not for the OVH API, so I would like request this feature, since the purpose of the API is facilitate and automate all this process. Also, I would like a better description of enum values in the OVH API console, because I am clueless to implement properly the scripts.

**Comment by shakaran** [comment]
UPDATE: I see in the GET operation the response class:

	type: domain.DomainLockStatusEnum: {
	-enum: [
	"locked"
	"locking"
	"unavailable"
	"unlocked"
	"unlocking"
	]

I try with "unlocking" value, but I receive the same error:

    Lock unavailable for your domain

**Comment by VincentCasse** [comment]
This problem seems not linked to the php-ovh projet but to your domain name service. Please contact the support to know why the lock is not available for your domain.
