### ISSUE TITLE
Using OVH PHP API

### ISSUE THREAD

**Issue by Pixuu** [ovh/php-ovh#54]
Hi!

I'm trying to make simple GET request to test how this API works. I have used many days for this but still haven't got this to work.

So I have Application Key, Application Secret and Consumer Key (with granted permissions to /*) and I have downloaded all the decencies (php-ovh-2.0.1-with-dependencies). I have correctly changed correct keys to example codes but they still are not working. I have tested keys with ovh python and that's simple, they are working. With all the examples on the page I get server error:

The * page isn’t working
* is currently unable to handle this request.

My ovh hosting is using PHP 5.4 and when using this page: https://api.ovh.com/console/ I can use all the GET reguest and they are working. Am I missing something or how this works? I don't have composer on my page.

**Comment by yadutaf** [comment]
Hi @Pixuu 

Can you paste the code you are using to issue the requests and call ``GET /auth/currentCredential`` with it ?

**Comment by Pixuu** [comment]
Hi!

I have this:

`require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;
use GuzzleHttp\Client;


$applicationKey = "xxxxxx";
$applicationSecret = "xxxxxx";
$consumer_key = "xxxxxx";


$endpoint = 'ovh-eu';

$conn = new Api(    $applicationKey,
                    $applicationSecret,
                    $endpoint,
                    $consumer_key);

echo "Welcome " . $ovh->get('/me')['firstname'];`


and my directory is looking like this:
http://puu.sh/sCKpk/13323a1d08.png
(script.php is my file)

**Comment by yadutaf** [comment]
What is the error message when you run it ?

**Comment by Pixuu** [comment]
The domain.com page isn’t working

domain.com is currently unable to handle this request.

**Comment by Pixuu** [comment]
For what version of PHP this is done? Or is there some syntax error which I don't see? (Its from OVH api...)

**Comment by Pixuu** [comment]
Still haven't got this to work, anyone has some example how I can simple run this?

**Comment by yadutaf** [comment]
Please provide the PHP and API errors, not the final browser visible page. We can not help you unless we have technical data. Thanks.

**Comment by Pixuu** [comment]
There is no errors from PHP or API, just that page.

**Comment by VincentCasse** [comment]
> The domain.com page isn’t working
> domain.com is currently unable to handle this request.

I think your domain name doesn't lead to your webhosting. But that's not an api issue. Can you check on support part of OVH customer panel?

**Comment by Pixuu** [comment]
My domain is on the ovh and its working great.

**Comment by Rbeuque74** [comment]
Hi, Can you send us a screenshot of what you see?
It doesn't look like an API error but a software problem on the infrastructure you are running the script

Romain

**Comment by Pixuu** [comment]
Okay I will explain this again from scratch.

I have customer panel where I would need some information from the API. I have downloaded and cloned this project and after that used composer to build this OVH API requirements. When project is composed I have these:

![ss 2016-12-07 at 11 50 33](https://cloud.githubusercontent.com/assets/11799536/20965056/d5e17c3c-bc7c-11e6-94d1-4f99d97cadc9.png)


and I edit to my script.php file correct API keys. So then I have this on my script.php
```

<?php

require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;
use GuzzleHttp\Client;


$applicationKey = "mykeytohere";
$applicationSecret = "mykeytohere";
$consumer_key = "mykeytohere";


$endpoint = 'ovh-eu';

$conn = new Api(    $applicationKey,
                    $applicationSecret,
                    $endpoint,
                    $consumer_key);

echo "Welcome " . $ovh->get('/me')['firstname'];
```

Then I upload all those files to my OVH host and try to open that script.php on my browser. Then I see the error:

![ss 2016-12-07 at 11 57 25](https://cloud.githubusercontent.com/assets/11799536/20965037/be323d60-bc7c-11e6-92b7-9cf46f4a4e70.png)

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

Usually those errors means that something is wrong in the PHP code. Should this work on PHP 5.4, because my OVH host uses that and I can't upload to PHP 7 (My other sites doesn't support that yet)?

I have also tried by downloading precompiled project from here:
https://github.com/ovh/php-ovh/releases
and use script.php but I get same error.

**Comment by Pixuu** [comment]
Still haven't got this to work, any ideas?

**Comment by Pixuu** [comment]
I have done some research with try catches and when I run this script on my localhost I get this:

cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

and there isn't any specific errors when I upload this to my OVH host, only the same:

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

On my host I am using OVH:s "Let's Encrypt Authority" free SSL certificate. I also tried with .htaccess file to disable ssl on that site but its not fixing anything. 

```
RewriteEngine On
RewriteCond %{HTTPS} on
RewriteRule ^ http://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
```

I think that this has something to do with SSL certificate, does this help?

**Comment by Rbeuque74** [comment]
Internal Server Error from your OVH host indicates there is a problem in your PHP file.
Can you access to errors logs (on linux server with Apache, it's usually /var/log/apache2/error_log) in order to detect what is the cause of the 500 error ?

**Comment by Pixuu** [comment]
My sites are on shared hosting so I don't have access those logs, there is some logs but they have nothing relevant information.

**Comment by Pixuu** [comment]
For example this is not getting me any server errors at this time:

`<head>
	<meta charset="UTF-8">
</head>

<?php
echo '1';
// This script is a skeleton of script or application using OVH APIs
// You can launch it with the command php script.php
// Or include it into a website be deleting the first line

require __DIR__ . '/vendor/autoload.php';
use\ Ovh\ Api;
use GuzzleHttp\ Client;

echo '2';

////////////////////////////////////////////////////
//     Dont forget to update your credentials     //
////////////////////////////////////////////////////

// Please read the documentation to get your credentials
// https://github.com/ovh/php-ovh
$applicationKey = "xxx";
$applicationSecret = "xxxx";
$consumer_key = "xxxx";

echo '3';
// Information about API and rights asked
$endpoint = 'ovh-eu';
$web_hosting = 'domain.com';
echo '4';
// Get API connector instance
$client = new Client();
$client->setDefaultOption( 'timeout', 1 );
$client->setDefaultOption( 'headers', array( 'User-Agent' => 'api_client' ) );

// Get servers list
$conn = new Api( $applicationKey,
	$applicationSecret,
	$endpoint,
	$consumer_key,
	$client );

echo '5';


try {
	echo $conn->get( '/me' )[ 'firstname' ];


	echo '6';

} catch ( GuzzleHttp\ Exception\ ClientException $e ) {
	echo '7';
	$response = $e->getResponse();
	$responseBodyAsString = $response->getBody()->getContents();
	echo $responseBodyAsString;
}


?>`

and it only prints 1234 to my site. I just can't understand whats the problem, I have tested and checked everything.

**Comment by Rbeuque74** [comment]
If you are running on shared hosting OVH, you can access your logs via The OVH manager, tab More, then Statistics and logs.
You should create an account and then click on  the logs.ovh.net link.
You should be able to get error_logs

**Comment by Pixuu** [comment]
Yeah there is only these from today (when I have tried to get this fixed):

[Fri Dec 09 17:51:02 2016] [error] [client 10.0.55.31] [host xxx.xxx.xxx] request failed: error reading the headers
[Fri Dec 09 18:23:58 2016] [error] [client xxx.xxx.xxx] [host xxx.xxx.xxx] client denied by server configuration: /homez.2078/melondiazi/www/asiakkaat/testi/.htaccess
[Fri Dec 09 18:51:02 2016] [error] [client xxx.xxx.xxx] [host xxx.xxx.xxx] request failed: error reading the headers

but those are not coming from this script, I have forum and it generates those errors.

**Comment by Pixuu** [comment]
Just took PHP example code from:
https://api.ovh.com/console/#/allDom#GET

and filled right information and downloaded right requirements and still not working. I'm not getting "internal server errors" anymore but page is still blank. Check it out here:
https://melondia.fi/testi/

script.php:
http://pastebin.com/jcxxdpKf

**Comment by Pixuu** [comment]
Any ideas how to get this to work? Any idea's are the problems on my OVH host or what's wrong? Or am I making the script wrong? Or is it the Php 5.4 why it's not working? Currently I don't have ideas how to fix or try this ovh php api some different way 😄

**Comment by Pixuu** [comment]
I tried to figure out this more and noticed that it can't handle connections:

$result = $ovh->get('/auth/currentCredential');

anything I do with connection->get, it's not doing it and I don't get any errors. I have try catch like this and it only prints number 7:

try {
	echo '7';
	$result = $ovh->get('/auth/currentCredential');
        print_r( $result );
        echo '8';
} catch (GuzzleHttp\Exception\ServerException $e) {
    $response = $e->getResponse();
    $responseBodyAsString = $response->getBody()->getContents();
    echo $responseBodyAsString;
	echo '9';
}

I printed this:
$ovh = new Api($applicationKey, $applicationSecret, $endpoint, $consumer_key);

Ovh\Api Object ( [endpoints:Ovh\Api:private] Array ( [ovh-eu] https://api.ovh.com/1.0 [ovh-ca]
=> https://ca.api.ovh.com/1.0 [kimsufi-eu]
=> https://eu.api.kimsufi.com/1.0 [kimsufi-ca]
=> https://ca.api.kimsufi.com/1.0 [soyoustart-eu]
=> https://eu.api.soyoustart.com/1.0 [soyoustart-ca]
=> https://ca.api.soyoustart.com/1.0 [runabove-ca]
=> https://api.runabove.com/1.0 ) [endpoint:Ovh\Api:private]
=> https://api.ovh.com/1.0 [application_key:Ovh\Api:private]
=> my_key_is_here [application_secret:Ovh\Api:private]
=> my_key_is_here [consumer_key:Ovh\Api:private]
=> my_key_is_here [time_delta:Ovh\Api:private]
=> [http_client:Ovh\Api:private]
=> GuzzleHttp\Client Object ( [config:GuzzleHttp\Client:private]
=> Array ( [timeout]
=> 30 [connect_timeout]
=> 5 [handler]
=> GuzzleHttp\HandlerStack Object ( [handler:GuzzleHttp\HandlerStack:private]
=> Closure Object ( [static]
=> Array ( [default]
=> Closure Object ( [static]
=> Array ( [default]
=> GuzzleHttp\Handler\CurlMultiHandler Object ( [factory:GuzzleHttp\Handler\CurlMultiHandler:private]
=> GuzzleHttp\Handler\CurlFactory Object ( [handles:GuzzleHttp\Handler\CurlFactory:private]
=> [maxHandles:GuzzleHttp\Handler\CurlFactory:private]
=> 50 ) [selectTimeout:GuzzleHttp\Handler\CurlMultiHandler:private]
=> 1 [active:GuzzleHttp\Handler\CurlMultiHandler:private]
=> [handles:GuzzleHttp\Handler\CurlMultiHandler:private]
=> Array ( ) [delays:GuzzleHttp\Handler\CurlMultiHandler:private]
=> Array ( ) ) [sync]
=> GuzzleHttp\Handler\CurlHandler Object ( [factory:GuzzleHttp\Handler\CurlHandler:private]
=> GuzzleHttp\Handler\CurlFactory Object ( [handles:GuzzleHttp\Handler\CurlFactory:private]
=> [maxHandles:GuzzleHttp\Handler\CurlFactory:private]
=> 3 ) ) ) [parameter]
=> Array ( [$request]
=> [$options]
=> ) ) [streaming]
=> GuzzleHttp\Handler\StreamHandler Object ( [lastHeaders:GuzzleHttp\Handler\StreamHandler:private]
=> Array ( ) ) ) [parameter]
=> Array ( [$request]
=> [$options]
=> ) ) [stack:GuzzleHttp\HandlerStack:private]
=> Array ( [0]
=> Array ( [0]
=> Closure Object ( [parameter]
=> Array ( [$handler]
=> ) ) [1]
=> http_errors ) [1]
=> Array ( [0]
=> Closure Object ( [parameter]
=> Array ( [$handler]
=> ) ) [1]
=> allow_redirects ) [2]
=> Array ( [0]
=> Closure Object ( [parameter]
=> Array ( [$handler]
=> ) ) [1]
=> cookies ) [3]
=> Array ( [0]
=> Closure Object ( [parameter]
=> Array ( [$handler]
=> ) ) [1]
=> prepare_body ) ) [cached:GuzzleHttp\HandlerStack:private]
=> ) [allow_redirects]
=> Array ( [max]
=> 5 [protocols]
=> Array ( [0]
=> http [1]
=> https ) [strict]
=> [referer]
=> [track_redirects]
=> ) [http_errors]
=> 1 [decode_content]
=> 1 [verify]
=> 1 [cookies]
=> [headers]
=> Array ( [User-Agent]
=> GuzzleHttp/6.1.1 curl/7.21.0 PHP/5.4.45 ) ) ) )


and it seems? to be right (I removed authentication keys).  Can I somehow test the connection?

$result = $ovh->get('/auth/currentCredential');

@yadutaf @VincentCasse @Rbeuque74

**Comment by Pixuu** [comment]
Got change to update one other of my sites to php 7 and tested there, seems to work like a charm. Not working with php 5.4

**Comment by Pixuu** [comment]
So I uploaded my script files to my php 7 host:
http://cafepepe.fi/Testi/testi/MelsScript.php

and to my main host where I want to get this to work (updated from php 5.4 -> 5.5 and then -> 5.6):
https://melondia.fi/wp/testi/MelsScript.php

and upper php 7 host works fine but php 5.6 host is not working. What's wrong? I don't understand @yadutaf @VincentCasse @Rbeuque74
