### ISSUE TITLE
Timeouts on requestPromised()

### ISSUE THREAD

**Issue by klanthier** [ovh/php-ovh#58]
I do not see anything in the documentation talking about timeouts.

Sometimes, my request sent to OVH never returns. That prevent me from either calling the .then() or the .catch(), resulting in a never ending request.

It would be great if there was a way to add a timeout that would fail the request after a certain amount of time, let's say 3 minutes.

Let me know !

**Comment by rbeuque74** [comment]
Hello,
This issue seems to be related to `nodejs-ovh` and not `php-ovh`.
Closing as stalled. Feel free to reopen in case I'm mistaken.

Romain
