### ISSUE TITLE
Guzzle HTTPClient throwing unnecessary exceptions

### ISSUE THREAD

**Issue by boindil** [ovh/php-ovh#6]
When trying to communicate with the OVH.eu API often exceptions (e.g. 404) are thrown.

For example on "GET /ip/{ip}/reverse/{ipReverse}" it returns a message and a 404. By default Guzzle throws exceptions rendering all own code totally useless. The message cannot be evaluated and the code stops executing.

**Comment by VincentCasse** [comment]
Hi boindil,

We're using Guzzle to use standardized solution for HTTP layer.
Indeed, Guzzle reports all "HTTP error" as an exception, but you can catch it in some case to check if error code is 404 or not. If you catch the exceptions, you will prevent to stop your application.

**Comment by alkulinich** [comment]
Hi Vincent, 

You right, we can catch the exception and prevent application to stop, but message coming with 404 error will be lost anyway.
