### ISSUE TITLE
I can't retrieve the ID of a task using the PHP API

### ISSUE THREAD

**Issue by jmarcoslc** [ovh/php-ovh#61]
Hi,

Today i've started working with the OVH API to do a project to get finished my studies.

I'm trying to create a subdomain using the mentioned API, and it works (it create the subdomain). But however I can't retrieve the returned data that contains the ID with the "post" function, when I return the value of the variable $task, I'm getting always a null object.

To handle all the process i've build a custom class called OVHAPI, next i'll left the code that i've builded:

```
<?php

	require_once 'libs/php-ovh/vendor/autoload.php';

	use \Ovh\Api;
	use GuzzleHttp\Client;

	class OVHAPI {

	    private $application_key;
		private $application_secret;
		private $consumer_key;
		private $ovh;
		private $http_client;

	    function __construct() {
	    	require("ovh_conexion.php");

	    	$this->http_client = new Client([
				'timeout'         => 30,
				'connect_timeout' => 5,
			]);

	    	$this->ovh = new Api($this->application_key,
                $this->application_secret,
                'ovh-eu',
                $this->consumer_key,
                $this->http_client
            );
	    }

	    function __destruct() {
	        
	    }

	    function createSubdomain($sub_domain, $zone="cocohost.tk", $field_type="A", $target="149.56.108.120") {
	    	$task = $this->ovh->post('/domain/zone/'.$zone.'/record', array(
			    'fieldType' => $field_type,
			    'subDomain' => $sub_domain,
			    'target' => $target,
			    'ttl' => 'NaN'
			));

			$this->ovh->post('/domain/zone/'.$zone.'/refresh');

			return $task;
	    }
	}

?>
```

**Comment by trnsnt** [comment]
Hi jmarcoslc, 

In fact there is an issue with API using 'ttl' => 'NaN'. 
Waiting fix on OVH side, you can just remove the ttl. Default ttl will be used.

**Comment by VincentCasse** [comment]
Is the problem fix on API side?

**Comment by laadidi** [comment]
Hello, I tested the SMS sending script

I respected the example as in the docuementation, it does not work,

I had the table invalidReceivers which returns the number of recipient,

what is the probem, please help. 

`
sms-XXXXXX-1

Array
(
    [totalCreditsRemoved] => 0
    [invalidReceivers] => Array
        (
            [0] => +35XXXXXXXXXX
        )

    [ids] => Array
        (
        )

    [validReceivers] => Array
        (
        )

)
Array
(
)

`

**Comment by rbeuque74** [comment]
Closing inactive non-issue.

**Comment by fabianoEmmetsolution** [comment]
make sure that ur 'sender' is true
