### ISSUE TITLE
Registering domain

### ISSUE THREAD

**Issue by Hesesses** [ovh/php-ovh#66]
Is is possible to register domain by one post command?

Currently I need to do all these steps:
- create cart 
- add domain to cart
- assign cart to user
- get item id of the domain in cart
- configure item details
- checkout
- pay

**Comment by shakaran** [comment]
@Hesesses see https://github.com/ovh/order-cart-examples/blob/master/php/order.php

**Comment by rbeuque74** [comment]
Closing this inactive non-issue.
