### ISSUE TITLE
Pas de réponse du serveur .

### ISSUE THREAD

**Issue by nicolas15000** [ovh/php-ovh#67]
Bonjour, 

Je n'ai pas encore acheté de SMS dans cette interface :+1: 

https://www.ovhtelecom.fr/sms/

Par contre je suis inscrit chez OVH, et j'ai créé 2 tokens ici :+1: 
https://api.ovh.com/createToken/index.cgi?GET=/sms&GET=/sms/%2a&PUT=/sms/%2a&DELETE=/sms/%2a&POST=/sms/%2a

et ici :+1: 

https://eu.api.ovh.com/createToken/

Lorsque j'exécute le fichier PHP suivant, je n'ai pas de compte qui s'affiche :+1:  en essayant avec les 2 tokens
```

`<?php
require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;

session_start();

// Informations about your application
$applicationKey = "xxxxxxxxxxxxxxx";
$applicationSecret = "xxxxxxxxxxxxxxxxxxxx";
$consumer_key = "xxxxxxxxxxxxxxxxxxxxxxxx";
$endpoint = 'ovh-eu';

$conn = new Api(    $applicationKey,
                    $applicationSecret,
                    $endpoint,
                    $consumer_key);
     
$smsServices = $conn->get('/sms/');
foreach ($smsServices as $smsService) {

    print_r($smsService);
}

        
?>`
```

Par contre le petit programme de connexion marche :+1: et me donne mon nom :+1: 

```
`<?php
require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;

session_start();

// Informations about your application
$applicationKey = "your_app_key";
$applicationSecret = "your_app_secret";
$redirection = "http://your_url.ovh";

// Information about API and rights asked
$endpoint = 'ovh-eu';
$rights = array( (object) [
    'method'    => 'GET',
    'path'      => '/me*'
]);

// Get credentials
$conn = new Api($applicationKey, $applicationSecret, $endpoint);
$credentials = $conn->requestCredentials($rights, $redirection);

// Save consumer key and redirect to authentication page
$_SESSION['consumer_key'] = $credentials["consumerKey"];
header('location: '. $credentials["validationUrl"]);
...
?>` 

```
Donc je voudrais savoir si c'est parce que j'ai pas acheté de SMS que ça marche pas et que j'ai une blank page, sans erreur ?

**Comment by VincentCasse** [comment]
Bonjour,

Effectivement, le premier script va afficher l'ensemble des comptes SMS que tu auras souscrit sur ovh.fr. C'est donc normal que tu n'ai rien vu que tu n'a pas encore souscris à ces offres.

Je ferme ce ticket ne correspondant pas à un soucis du wrapper. Mais en cas d'autre soucis, il ne faut pas hésiter à en ouvrir un nouveau.

Bon courage dans le développement.
