### ISSUE TITLE
Bad request for DELETE /telephony/{billingAccount}/service/{serviceName}

### ISSUE THREAD

**Issue by alexandrejacq** [ovh/php-ovh#70]
Bonjour Vincent,

lors de l'appel à DELETE /telephony/{billingAccount}/service/{serviceName} j'ai un 400 Bad Request avec le message INVALID_SIGNATURE quelque soit les droits du token utilisé (DELETE sur /*) sur ce SDK (fonctionne sur d'autres SDK php avec les mêmes paramètres)
Avez-vous une idée de l'origine du blocage?
Merci
Alexandre

**Comment by brunobazille** [comment]
Hi,

Same issue with DELETE /domain/zone/{domainName}/record/{recordId}

Thanks for your help
Bruno

**Comment by fmh** [comment]
+1

**Comment by Rbeuque74** [comment]
Hello guys,
Can you provide a debugging response header "X-OVH-QUERYID" to be able to investigate deeper on OVH side.
Thanks

Romain

**Comment by fmh** [comment]
in my case i resolved my issue, some data wrong in my request

**Comment by Rbeuque74** [comment]
To close ? @VincentCasse

**Comment by VincentCasse** [comment]
Yes, you're right. This issue is not link to the SDK but to the API behavior. 

I close
