### ISSUE TITLE
Multiple access rules

### ISSUE THREAD

**Issue by AntoineCheminat** [ovh/php-ovh#73]
Hi, I'l like to create a Token for both GET and POST methods but i don't find the right way to do it
How would the $rights look like with multiple methods ? 
Thank you. 

SOLVED :

i used 

$ovh = new Api(APP_KEY, APP_SECRET, APP_ENDPOINT);
$credentials = $ovh->post('/auth/credential', array(
    'accessRules' => array(
        array("method" => "GET","path" => "/*"),
        array("method" => "POST","path" => "/*"),
        array("method" => "PUT","path" => "/*"),
        array("method" => "DELETE","path" => "/*")
    ),
    'redirection' => $redirection,
));
etc ....

Hope it will help.

peace

**Comment by Rbeuque74** [comment]
Hello @AntoineCheminat ,
Please use the official OVH API mailing-list for asking help.
You can find a way to subscribe to the mailing-list at the bottom of https://api.ovh.com/ page.

Closing this non-issue.
