### ISSUE TITLE
easily generate restricted rights

### ISSUE THREAD

**Issue by jsaada** [ovh/php-ovh#75]
hello,

i write those few lines, maybe you could integrate it on a debug mode ?

it shows on the syslog the exaustive calls from the application
```
$pathstared= preg_replace("/[0-9a-f]{32}/i","*",$path);
$pathstared= preg_replace("/[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}/","*",$pathstared);
syslog(LOG_INFO,"${method}=${pathstared}&");
```

output on syslog:
```
 GET=/cloud/project/*/instance&
 GET=/cloud/project/*/ip/failover&
 GET=/status/task&
 POST=/cloud/project/*/ip/failover/*/attach&
 GET=/me&
 GET=/cloud/project/*/instance&
 GET=/cloud/project/*/ip/failover&
```
we can then easily generate restricted rights for the app
```
egrep 'GET|POST|DELETE|PUT' /var/log/syslog|egrep -v 'auth/time|ERROR'|cut -d' ' -f6|sort|uniq|tr -d "\n"
```
the goal is of course to create keys for just what is necessary
https://api.ovh.com/createToken/index.cgi?GET=/cloud/project/*/instance&GET=/cloud/project/*/ip/failover&GET=/me&GET=/status/task&POST=/cloud/project/*/ip/failover/*/attach&

**Comment by rbeuque74** [comment]
Hello,
Closing as stalled. Feel free to reopen if still relevant.

Romain
