### ISSUE TITLE
Delete a failover IP is deprecated 

### ISSUE THREAD

**Issue by Gaditanian** [ovh/php-ovh#79]
Does it mean that I can't delete a failover ip through the api?

**Comment by rbeuque74** [comment]
Hello @Gaditanian,
Which route are you referring ?
Every deprecated routes are given with a replacement routes in the schema, so you can migrate before the complete deprecation and deletion.

Regards,
Romain

**Comment by Gaditanian** [comment]
Hell @rbeuque74, thanks for replying.

This is the api call:

POST /ip/{ip}/terminate 
Delete a failover IP
Api Status : DEPRECATED

I don't find the alternative.

**Comment by rbeuque74** [comment]
Hey @Gaditanian,
Can you try the alternative POST /ip/service/{serviceName}/terminate call ?
If your IP address is a service billed every month, you should be able to terminate the subscription with this call.

Romain

**Comment by rbeuque74** [comment]
Issue stalled.
Closing

**Comment by meetsohail** [comment]
HI @rbeuque74 ,

I think the service terminate endpoint will terminate all IPs under service! I need to terminate specific IPs under service! Is there a way to terminate specific IPs?
