### ISSUE TITLE
requestCredentials() always returns 401

### ISSUE THREAD

**Issue by chief-kh** [ovh/php-ovh#87]
Hi
I have updated library to the latest version and now method requestCredentials() always returns
`401 Unauthorized` response:
{"message":"You must send your application key to request new credentials"}

Solution:
in file Api.php I moved line #287:
$headers['X-Ovh-Application'] = $this->application_key;
to line #284 (before if statement)

**Comment by cautbur** [comment]
Calling this function with authentication setted to true on function requestCredentials worked for me. Only have to change the last parameter on line 208 from false to true.

**Comment by rbeuque74** [comment]
Fixed in #94
