### ISSUE TITLE
DELETE order cart error

### ISSUE THREAD

**Issue by prinick96** [ovh/php-ovh#88]
Good, at this moment I am in a client area for my web, where I plan to offer all the dedicated, clouds and OVH domains for my clients.
In the integration, I am carrying out the shopping cart and I have overcome the problem of removing the domain, the cart from the OVH through the API, obtaining an error.

```bash
DELETE https://api.ovh.com/1.0/order/cart/f9fca869-999c-411b-a5da-dfd25c8a6f57/item/62261689
resulted in a `403 Forbidden` response:
{"errorCode":"NOT_GRANTED_CALL","httpCode":"403 Forbidden","message":"This call has not been granted"}
```

I have verified the data I send and they are correct, in fact since the tool in the documentation works for me. I'm using the api's PHP SDK to make the DELETE request and I get that error, it's the point where my clients remove a domain from their cart, so I must also remove it from the cart in OVH.

The credentials to connect to OVH are not wrong, since I use the same instance with which I add things to the cart.

Regards

**Comment by prinick96** [comment]
I have this!

```php
 $this->ovh = new Api(
            $config['ovh']['key'],
            $config['ovh']['secret'],
            $config['ovh']['endpoint'],
            $config['ovh']['consumer']
);
$this->ovh->delete('/order/cart/'. $cartId . '/item/' . $itemId);
```

**$cartId** and **itemId** are corrects.

**Comment by rbeuque74** [comment]
You seems to have generated a consumerKey to grant only GET /* and POST
/*, you are perfoming a DELETE request, hence the NOT_GRANTED_CALL.
Your credential IS invalid, please generate a new one with DELETE calls
granted.

For example:
```php
// Information about API and rights asked
$endpoint = 'ovh-eu';
$rights = array( (object) [
    'method'    => 'DELETE',
    'path'      => '/*'
], (object) [
    'method'    => 'GET',
    'path'      => '/*'
], (object) [
    'method'    => 'POST',
    'path'      => '/*'
]);

// Get credentials
$conn = new Api($applicationKey, $applicationSecret, $endpoint);
$credentials = $conn->requestCredentials($rights, $redirection);
```

Closing as not related to php-ovh

Romain
