### ISSUE TITLE
Problem deleting some domain types

### ISSUE THREAD

**Issue by jfirles** [ovh/php-ovh#89]
Hi,

I'm using the api from my webpage for creating and deleting records of some domains in ovh, but the las few weeks I have problems deleting.

I have problems deleting some register types like SRV.

This is my sample script in php using your sdk:

The code in pastebin:
https://pastebin.com/eV8iQuy3

<?php

$applicationKey = "myAppKey";
$applicationSecret = "myAppSecret";
$consumer_key = "myConsumerKey";

$endpoint = "ovh-eu";

require __DIR__ . '/vendor/autoload.php';
use \Ovh\Api;

$ovh = new Api( $applicationKey,
                $applicationSecret,
                $endpoint,
                $consumer_key);

$response = $ovh->get('/domain/zone/mydomain.com/record?fieldType=SRV&subDomain=_sip._udp.mysubdomain');

print_r($response);
// this returns 1 record id, for example 1583058551

// delete record
$response = $ovh->delete('/domain/zone/mydomain.com/record/1583058551');

print_r($response);

?>

If I execute the script:

The execution in pastebin:
https://pastebin.com/ZPxfZ8GK

php -q test.php 
Array
(
    [0] => 1583058551
)
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `DELETE https://api.ovh.com/1.0/domain/zone/mydomain.com/record/1583058551` resulted in a `404 Not Found` response:
{"message":"The requested object (id = 1583058551) does not exist"}
 in /home/test/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /home/test/php/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/test/php/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/test/php/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/test/php/vendor/guzzlehttp/promises/src/TaskQueue.php(60): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /home/test/php/vendor/g in /home/test/php/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107

I'am using the api incorrectly?

Other records like "A" records I can delete, so, It is not a permission problem.

If you need another information, please ask me.

Best regards

**Comment by rbeuque74** [comment]
Hello,

I guess this issue is out-dated. If you still have a problem with this code, feel free to re-open the issue, with the corresponding `X-Ovh-Query-Id` response headers so we can track the request on our side.

Romain
