### ISSUE TITLE
Provide an alternative to setPassword

### ISSUE THREAD

**Issue by jo66** [ovh/php-ovh#90]
Hi,

The `/vps/{serviceName}/setPassword` method returns this on my VPS (SSD1-2018):
"This function is not available on your VPS"

From the OVH support:
> Cet appel API est déprécié. Il est désormais proposé pour les VPS 2014.

I guess it was deprecated for security reasons, but **API should provide an alternative way to set password, or at least any other way to connect in ssh from script to VPS newly ordered with API**.

I agree to contribute with a PR but I need help.

I really don't want my script to fetch mails to obtain password, it would be very ugly!

Regards

**Comment by Alkorin** [comment]
You can use OVH Public Cloud and set a SSH public key when you start your instances.
And then, no more password ;)

**Comment by jo66** [comment]
I am not specialist in OVH offers but Public Cloud involves monthly fees right?

**Comment by jo66** [comment]
A better solution than fetching email is to use API to get notifications.
Seems that it's also possible to use ssh key by reinstalling VPS with ` /vps/{serviceName}/reinstall`.
Since ssh key is more secure than password I will close this issue for #91
