### ISSUE TITLE
How to add another paths

### ISSUE THREAD

**Issue by need4android-com** [ovh/php-ovh#96]
`$endpoint = 'ovh-eu';
$rights = array( (object) [
    'method'    => 'GET',
    'path'      => '/me*'
  ]);`
How  to add another paths ?

I've tried this:
`$endpoint = 'ovh-eu';
$rights = array( (object) [
    'method'    => 'GET',
    'path'      => '/me*',
    'path'      => '/cloud*'
]);`

but didn't work?

**Comment by rbeuque74** [comment]
Hello,
I guess the correct way to do this is:

```php
$rights = array( (object) [
    'method'    => 'GET',
    'path'      => '/me*'
],  (object) [
    'method'    => 'GET',
    'path'      => '/cloud*'
]);
```

Tell me if this is fixing your issue.
Romain

**Comment by rbeuque74** [comment]
Closing. Please reopen if you still have an issue :)

Romain

**Comment by need4android-com** [comment]
> Closing. Please reopen if you still have an issue :)
> 
> Romain



> Hello,
> I guess the correct way to do this is:
> 
> ```
> $rights = array( (object) [
>     'method'    => 'GET',
>     'path'      => '/me*'
> ],  (object) [
>     'method'    => 'GET',
>     'path'      => '/cloud*'
> ]);
> ```
> 
> Tell me if this is fixing your issue.
> Romain

I've set path to :  'path'      => '/*' and it works fine!
