### ISSUE TITLE
OVH PHP 2.0.1 Not Working Guzzle 6.5.2

### ISSUE THREAD

**Issue by BimoSora** [ovh/php-ovh#99]
dear.. ovh
the code using guzzle is not working on me. 
can you give the native version?

What I'm confused about, OVH VPS can't run vendor / ovh

https://pastebin.com/raw/YdTwkB5B

![Screenshot_20200313-155843](https://user-images.githubusercontent.com/16408431/76605723-8b26a000-6543-11ea-965e-4df9191ceba2.jpg)
![Screenshot_20200313-160225](https://user-images.githubusercontent.com/16408431/76606127-4fd8a100-6544-11ea-8653-93499548f40e.jpg)

**Comment by bistory** [comment]
Guzzle 7 is out and is required by Laravel 8, thus OVH break compatibility with newer frameworks.

Could someone please fix that or merge #41 ?
